version: '3.1'

services:
  front:
    image: danisrcnl/ai-project-frontend:1.0
    ports:
      - "4200:4200"
  back:
    image: danisrcnl/ai-project-backend:1.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/teams?autoReconnect=true&useSSL=false
  mysql:
    image: danisrcnl/ai-project-db:2.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=teams
